import * as fs from 'node:fs'
import { EOL } from 'node:os'
import { build } from 'template-language'

const result = await build('template.tln')
const output = `/* generated by \`node script.js\` */${EOL}${result.content}`
fs.writeFileSync('my-scripted-output.ts', output, 'utf8')
