#!/usr/bin/env node
import * as fs from 'node:fs'
import * as path from 'node:path'
import { EOL } from 'node:os'
import { print } from './printer'
import { build } from './build'

const [, , ...args] = process.argv
const [templatePathInput, ...slotsInput] = args

/**
 * @TODO outdir?
 * @TODO just emit to stdout? (no need for outdir)
 */

const templatePath = path.resolve(templatePathInput)
print.info('template path is', templatePath)
const slots = slotsInput.reduce((acc, slot) => {
  const [name, value] = slot.split('=')
  return {
    ...acc,
    [name.replace(/^--/, '')]: value,
  }
}, {})
print.info('slots are', slots)
print.info('build start')
const built = await build(templatePath, slots)
print.info('build end')
const output = `/* generated by template-language */${EOL}${built.content}`
const outfile = path.join(
  path.dirname(templatePath),
  `${path.basename(templatePath, path.extname(templatePath))}.${
    built.extension
  }`
)
print.info('determined outfile is', outfile)
print.info('write start')
fs.writeFileSync(outfile, output, 'utf-8')
print.info('write end')
